version: "3.9"
services:
  webapi:
    build: .
    container_name: webapi    
    ports:
      - 80
    environment:
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=S0rt3
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.pfx
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - database
    # volumes:
    #   - ./src/lib/Infrastructure/Database/Scripts/create_database.sql:/tmp/create_database.sql
    #   - ./src/lib/Infrastructure/Database/Scripts/init-database.sh:/tmp/init-database.sh
    # command: /bin/bash ./tmp/init-database.sh