version: "3.9"
services:
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=VeryComplex123Password
    networks:
      - backend-network
  webapi:
    build: .
    container_name: webapi    
    ports:
      - 80
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT:Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRING=Server=database;Database=ccs;User=sa;Password=VeryComplex123Password;
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=S0rt3
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=certificate.pfx
    networks:
      - backend-network

networks:
  backend-network: